### ISSUE TITLE
[Research] 與 17 請款格式

### ISSUE THREAD

**Issue by clairepeng0808** [mithio/vault-business-dashboard#1]
### Desc

目前 17 x MITH x Max 三方合作案，我們每個月會需要與 17 請款，請款格式如下
https://docs.google.com/spreadsheets/d/1z7UNPD3OSUFLohn_G1IPlXjQ2sTrk49x9jDZ_9w-_Kc/edit#gid=0

每月七號前，我們須提供前個月的請款表單
我目前正在思考是否可以做在商家後台
給 17 一組帳號密碼登入，他們可以自己查看
並匯出表單，這樣就不用我們每月手動輸出表單

但想請 Tony 評估一下是否可行
大概需要多少時間
然後跟 CMJ 對一下資料格式

**Comment by clairepeng0808** [comment]
此 repo 我無法assign人
是否要開權限給我
@M157q @chuchuhao

**Comment by chuchuhao** [comment]
資料撈取的方法
1. 最暴力 (不保險, 以後可能會支援其他 currency = TWD, USD的情況
撈 withdraw currency = TWD, deposit currency = USD

2. 普通暴力 (不保險, 可能直播主尚未完成提款 只是轉帳完成
撈 user的 oauth-app-token = m17streamer的 deposit/ withdraw紀錄

3. 決定使用的方法 
等專屬 max的 table上 staging之後在測試

可以先完成頁面設計 (side bar名稱 以及頁面排版)

**Comment by clairepeng0808** [comment]
好的，財務那邊會在跟他們開會
我這邊確定格式再開實作票給兩位！
先關閉 @cmj @chuchuhao
